### ISSUE TITLE
Remove role restrictions from role selection

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-core#8]
Removing the role restrictions from the player role selection screen.

ie. UAV operator, engineer, etc..
Only one that can remain would be medic.

@jonpas Did ACE have an option to do this?

**Comment by jonpas** [comment]
Did a search through, that's what I did for 1.3.0.

- Repair
  - Allow Repair (Who can perform repair actions?) `engineerSetting_Repair` -> Anyone
  - Full Repair Locations (At what location can a vehicle be fully repaired) `fullRepairLocation` -> Repair Facility or Vehicle (some are by default set like repair trucks, any building, object or vehicle can be manually set via a module or a variable)
  - Allow Full Repair (Who can perform a full repair on a vehicle?) `engineerSetting_fullRepair` -> Anyone (as long as in repair location)
- Add Spare Parts (Add spare parts to vehicles?) `addSpareParts` - > No (because there is a separate module to add them and for Chronos compatibility we don't want them being added by default)
